#!/usr/bin/env bash
# Install a git post-merge hook on THIS clone so `git pull` auto-stamps app/custom/GIT_COMMIT
# in each job dir. Run ONCE on the submit host (the machine you submit NVFLARE jobs from).
# After that, every `git pull` refreshes the stamp to the new HEAD -- no manual step before
# submit, and nothing to do on the client machines (the file ships with the job).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK="$ROOT/.git/hooks/post-merge"

cat > "$HOOK" <<'HOOK_EOF'
#!/usr/bin/env bash
# Auto-generated by tools/install_git_hooks.sh. Stamps the commit into each job's
# app/custom/GIT_COMMIT after every `git pull` (merge), so deployed runs are attributable.
ROOT="$(git rev-parse --show-toplevel)"
if [ -x "$ROOT/tools/stamp_git_commit.sh" ]; then
  "$ROOT/tools/stamp_git_commit.sh" || true
fi
HOOK_EOF
chmod +x "$HOOK"
echo "Installed post-merge hook -> $HOOK"
echo "Stamping now for the current HEAD..."
"$ROOT/tools/stamp_git_commit.sh"
